# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - "main"
  pull_request:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: stable
    - working-directory: gohelloserverless
      run: go build -v ./...
    - working-directory: gohelloserverless
      run: go test -v ./...
    - uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        working-directory: gohelloserverless
